In [1]:
import pandas as pd

Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})

In [2]:
Hut_Paradise_DF

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40

In [3]:
Hut_Paradise_values = Hut_Paradise_DF.values

In [8]:
Hut_Paradise_values[4]

array([40, 33,  1,  6, 20, 16], dtype=int64)

In [2]:
import numpy as np

In [14]:
a = np.array(Hut_Paradise_DF['2.Area'])
b = np.array(Hut_Paradise_DF['6.Liv.Area'])
a-b

array([13, 12, 15, 13, 17,  9, 20, 15, 25], dtype=int64)

In [15]:
t = np.array([10, 20, 30, 15, 5, 40, 20, 8, 20])
p = np.array(Hut_Paradise_DF['5.Demo two weeks'])
np.dot(t, p)

1348

In [16]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

In [18]:
m = 2*v + -3*w

In [19]:
np.dot(u, m)

0

In [1]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

In [4]:
Husband = Husband_Income-Husband_Consumption
Wife = Wife_Income-Wife_Consumption
Mother_In_Law = Mother_In_Law_Income-Mother_In_Law_Consumption

In [11]:
matrix = np.array([Husband, Wife, Mother_In_Law])
matrix = matrix.T
matrix

array([[ 50,  50, -10],
       [170, 120,  60],
       [ 80, -10, -40]])

In [12]:
matrix_income = np.array([Husband_Income, Wife_Income, Mother_In_Law_Income])
matrix_income = matrix_income.T
matrix_income

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

In [13]:
matrix_cons = np.array([Husband_Consumption, Wife_Consumption, Mother_In_Law_Consumption])
matrix_cons = matrix_cons.T
matrix_cons

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

In [16]:
matrix_inc = matrix_income*0.87

In [17]:
P = matrix_inc-matrix_cons
P

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

In [19]:
A = np.matrix('1, -5; 2, 2; 0, 3')
B = np.matrix("3, 1, 0; -1, 0, 2")

In [20]:
A

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

In [21]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

In [23]:
A@x

array([26, 30])

In [24]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

In [25]:
B@A

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [29]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

In [30]:
A = np.array([x,y,z])

In [31]:

A

array([[ 1,  2,  1,  0,  4],
       [ 2,  1, -1,  1,  0],
       [-1,  1, -1,  0,  0]])

In [32]:
G = A.T@A

In [33]:
G

array([[ 6,  3,  0,  2,  4],
       [ 3,  6,  0,  1,  8],
       [ 0,  0,  3, -1,  4],
       [ 2,  1, -1,  1,  0],
       [ 4,  8,  4,  0, 16]])

In [34]:
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)


In [37]:
A = Count_DF.values
B = Price_DF.values
print(A)
print()
print(B)

[[10  5 12 15 10]
 [ 2 21  3 25  6]
 [12 12  0 30  4]
 [ 4  8 18 14  5]
 [ 6 25 27 25 18]
 [10  3  2 17 12]
 [22  1  4 25 20]
 [ 7  0 31 31 28]]

[[2.  1.5 1.  0.8 1. ]
 [1.8 2.5 1.  1.  1. ]
 [2.  2.  0.  0.5 2. ]
 [1.8 1.2 2.8 0.8 2. ]
 [2.5 3.5 2.  1.  1.5]
 [5.  5.  3.  2.  2.5]
 [1.1 1.  1.5 0.5 1.7]
 [4.5 4.  2.5 1.  2. ]]


In [ ]:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])


In [1]:
import numpy as np

In [2]:
A = np.matrix('2,0,0;0,1,0;0,0,4')
A

matrix([[2, 0, 0],
        [0, 1, 0],
        [0, 0, 4]])

In [3]:
np.linalg.det(A)

7.999999999999998

In [6]:
round(np.linalg.det(np.linalg.inv(A)), 3)

0.125

In [7]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])

In [9]:
A_inv = np.linalg.inv(A)
A_inv

array([[-1.875  ,  2.3125 , -0.03125],
       [ 0.375  , -0.5625 ,  0.15625],
       [ 1.25   , -1.375  , -0.0625 ]])

In [10]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

In [11]:
A = np.array([v1,v2,v3,v4]).T

In [13]:
rk = np.linalg.matrix_rank(A)
rk

4

In [14]:
G = A.T@A
G

array([[360,  96,  73, -35],
       [ 96,  46,  16,   4],
       [ 73,  16,  33,   4],
       [-35,   4,   4,  51]])

In [15]:
np.linalg.det(G)

3716647.9999999995

In [16]:
G_inv = np.linalg.inv(G)
G_inv

array([[ 0.01711488, -0.02798543, -0.02623063,  0.01599775],
       [-0.02798543,  0.071967  ,  0.03031441, -0.02722776],
       [-0.02623063,  0.03031441,  0.07683106, -0.02640498],
       [ 0.01599775, -0.02722776, -0.02640498,  0.03479318]])

In [3]:
A = np.matrix('1,-5;2,1;1,1')

In [4]:
b = np.array([1,2,2]).T

In [5]:
b_pred = (np.linalg.inv(A.T@A))@A.T@b

In [7]:
e = b - b_pred

Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "C:\Users\Anna\AppData\Roaming\Python\Python39\site-packages\IPython\core\interactiveshell.py", line 3378, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\Anna\AppData\Local\Temp\ipykernel_5936\995970441.py", line 1, in <module>
    e = b - b_pred
ValueError: operands could not be broadcast together with shapes (3,) (1,2) 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Anna\AppData\Roaming\Python\Python39\site-packages\IPython\core\interactiveshell.py", line 1997, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "C:\Users\Anna\AppData\Roaming\Python\Python39\site-packages\IPython\core\ultratb.py", line 1112, in structured_traceback
    return FormattedTB.structured_traceback(
  File "C:\Users\Anna\AppData\Roaming\Python\Python39\site-packages\IPython\core\ultratb.py", line 1006, in structured_traceback
    retu

In [15]:
A = np.matrix('12,0;0,10')
A

matrix([[12,  0],
        [ 0, 10]])

In [16]:
b = np.linalg.inv(A)
b

matrix([[0.08333333, 0.        ],
        [0.        , 0.1       ]])

In [17]:
b.shape

(2, 2)

In [18]:
c = np.array([-16,6]).T

In [19]:
b@c

matrix([[-1.33333333,  0.6       ]])