In [1]:
import numpy as np # для работы с массивами
import pandas as pd # для работы с DataFrame 
from sklearn import datasets # для импорта данных
import seaborn as sns # для визуализации статистических данных
import matplotlib.pyplot as plt

In [2]:
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'PRICE']
data = pd.read_csv('data/housing.csv', header=None, delimiter=r"\s+", names=column_names)
data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  PRICE  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2

In [3]:
CRIM = data['CRIM']
RM = data['RM']
A = np.column_stack((np.ones(506), CRIM, RM))
y = data[['PRICE']]
w = np.linalg.inv(A.T@A)@A.T@y
print('w:' , w.values)

from sklearn.linear_model import LinearRegression

model = LinearRegression(fit_intercept=False)
model.fit(A, y)
print('w:', model.coef_.T)

CRIM_new = 0.1
RM_new = 8
new = np.array([[1, CRIM_new, RM_new]])
new_prediction = model.predict(new)
print('prediction:', new_prediction)

w: [[-29.24471945]
 [ -0.26491325]
 [  8.39106825]]
w: [[-29.24471945]
 [ -0.26491325]
 [  8.39106825]]
prediction: [[37.85733519]]


In [4]:
A = data[['CHAS', 'LSTAT', 'CRIM','RM']]
y = data[['PRICE']]
# стандартизируем векторы в столбцах матрицы A
A_cent = A - A.mean()
A_st = A_cent/np.linalg.norm(A_cent, axis=0)
A_st.describe().round(2)

CHAS   LSTAT    CRIM      RM
count  506.00  506.00  506.00  506.00
mean    -0.00   -0.00   -0.00   -0.00
std      0.04    0.04    0.04    0.04
min     -0.01   -0.07   -0.02   -0.17
25%     -0.01   -0.04   -0.02   -0.03
50%     -0.01   -0.01   -0.02   -0.00
75%     -0.01    0.03    0.00    0.02
max      0.16    0.16    0.44    0.16

In [17]:
x_1 = np.array([5.1,1.8,2.1,10.3,12.1,12.6])
x_2 = np.array([10.2,3.7,4.1,20.5,24.2,24.1])
x_3 = np.array([2.5,0.9,1.1,5.1,6.1,6.3])



In [19]:

A = np.array([x_1, x_2, x_3]).T


array([[ 5.1, 10.2,  2.5],
       [ 1.8,  3.7,  0.9],
       [ 2.1,  4.1,  1.1],
       [10.3, 20.5,  5.1],
       [12.1, 24.2,  6.1],
       [12.6, 24.1,  6.3]])

In [22]:
np.corrcoef(A)

array([[1.        , 0.99983718, 0.99998836, 1.        , 0.99997637,
        0.99983421],
       [0.99983718, 1.        , 0.9999126 , 0.99983718, 0.9999376 ,
        0.99934286],
       [0.99998836, 0.9999126 , 1.        , 0.99998836, 0.9999979 ,
        0.99973473],
       [1.        , 0.99983718, 0.99998836, 1.        , 0.99997637,
        0.99983421],
       [0.99997637, 0.9999376 , 0.9999979 , 0.99997637, 1.        ,
        0.99968542],
       [0.99983421, 0.99934286, 0.99973473, 0.99983421, 0.99968542,
        1.        ]])

In [28]:
np.linalg.matrix_rank(A)

3

In [32]:
np.linalg.det()

Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "C:\Users\Anna\AppData\Roaming\Python\Python39\site-packages\IPython\core\interactiveshell.py", line 3378, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\Anna\AppData\Local\Temp\ipykernel_10440\3080697549.py", line 1, in <module>
    np.linalg.det()
  File "<__array_function__ internals>", line 179, in det
TypeError: _unary_dispatcher() missing 1 required positional argument: 'a'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Anna\AppData\Roaming\Python\Python39\site-packages\IPython\core\interactiveshell.py", line 1997, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "C:\Users\Anna\AppData\Roaming\Python\Python39\site-packages\IPython\core\ultratb.py", line 1112, in structured_traceback
    return FormattedTB.structured_traceback(
  File "C:\Users\Anna\AppData\Roaming\Python\Python39\site-packages\IPython\co

In [33]:
A = np.matrix(A)
print(np.linalg.det(A))

Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "C:\Users\Anna\AppData\Roaming\Python\Python39\site-packages\IPython\core\interactiveshell.py", line 3378, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\Anna\AppData\Local\Temp\ipykernel_10440\1356713797.py", line 2, in <module>
    print(np.linalg.det(A))
  File "<__array_function__ internals>", line 180, in det
  File "c:\Users\Anna\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\linalg\linalg.py", line 2151, in det
    _assert_stacked_square(a)
  File "c:\Users\Anna\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\linalg\linalg.py", line 204, in _assert_stacked_square
    raise LinAlgError('Last 2 dimensions of the array must be square')
numpy.linalg.LinAlgError: Last 2 dimensions of the array must be square

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Anna\AppData\Roaming\Python\Python39\site-package

In [1]:
import numpy as np

A = np.array([
    [1, 1, 1, 1],
    [1, 3, -2, 9],
    [1, 9, 4, 81]
]).T
y = np.array([3, 7, -5, 21])
w_hat = np.linalg.inv(A.T@A)@A.T@y
print(w_hat) 

[ 0.11446013  2.46095638 -0.01608801]


In [4]:
from sklearn.linear_model import Ridge
A = np.array([
    [1, 1, 1, 1, 1],
    [5,9,4,3,5],
    [15,18,18,19,19],
    [7,6,7,7,7]
]).T
# вектор целевого признака
y = np.array([24,22,35,33,36])
# получаем оценку коэффициентов регрессии по МНК с регуляризацией Тихонова
ridge = Ridge(alpha=1, fit_intercept=False)
ridge.fit(A, y)
print(ridge.coef_.round(2)) 

[-0.09 -1.71  1.91  0.73]


In [5]:
from sklearn.linear_model import ElasticNet
A = np.array([
    [1, 1, 1, 1, 1],
    [1, 0, -3, 2, 4],
    [2, 0, -6, 4, 8]
]).T
# вектор целевого признака
y = np.array([4, 3, -4, 2, 7])
# получаем оценку коэффициентов регрессии 
elasticnet = ElasticNet(alpha=0.1, l1_ratio=0.2, fit_intercept=False)
elasticnet.fit(A, y)
print(elasticnet.coef_)
## [1.13492457 0.19525842 0.6237965 ]

[1.13492457 0.19525842 0.6237965 ]
